import Head from 'next/head'
import Image from 'next/image'
import {useState, useEffect, useCallback} from 'react'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {history} from '@/lib/history'
import {UGen, zen, float, input, ZenGraph} from '@/lib/zen'
import {mult, ceil, wrap, add, sub, mix, div, floor} from '@/lib/math'
import {phasor} from '@/lib/phasor'
import {data, peek, poke} from '@/lib/data'
import {createWorklet} from '@/lib/worklet'
import {zswitch} from '@/lib/switch';
import {lt, rampToTrig} from '@/lib/delta';
import {latch} from '@/lib/latch';
import {scale} from '@/lib/scale';
import {triangle} from '@/lib/triangle';
import {noise} from '@/lib/noise';
import {delay} from '@/lib/delay';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const [workletCode, setWorkletCode] = useState<string>("");

    useEffect(() => {
        window.addEventListener("mousedown", start);
    }, []);

    const start = useCallback(() => {
        let voice = phasor(48.8);
        const tri = triangle(
            phasor(
                latch(floor(add(80, mult(voice, 360))),
                      rampToTrig(phasor(40))
                     ),
            ),
            scale(phasor(.1), 0, 1, .01, .99)
        );

        const graph1 = delay(tri, 20000);
            
            

        let ctxt = new AudioContext();
        createWorklet(ctxt, zen(graph1)).then(
            x => {
                setWorkletCode(x.code);
                x.workletNode.connect(ctxt.destination);
            });
    }, []);

    return (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className="flex flex-col text-xs w-full h-full">
            <div className="rounded-lg  mt-8 m-auto p-5 bg-white text-black">
              <pre>
                <code>
                  {workletCode}
                </code>
              </pre>
            </div>
          </main>
        </>
    );
}
