import Head from 'next/head'
import Image from 'next/image'
import {useState, useEffect, useCallback} from 'react'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {history} from '@/lib/history'
import {UGen, zen, float, input, ZenGraph} from '@/lib/zen'
import {mult, wrap, add, sub, mix} from '@/lib/math'
import {phasor} from '@/lib/phasor'
import {createWorklet} from '@/lib/worklet'
import {rampToTrig} from '@/lib/delta';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const [workletCode, setWorkletCode] = useState<string>("");

    useEffect(() => {
        window.addEventListener("mousedown", start);
    }, []);

    const start = useCallback(() => {

        const graph1: ZenGraph = zen(
            wrap(phasor(90, phasor(8)), 0, wrap(phasor(1.2), 0, 0.2))
        );

        let ctxt = new AudioContext();
        createWorklet(ctxt, graph1).then(
            x => {
                setWorkletCode(x.code);
                x.workletNode.connect(ctxt.destination);
            });
    }, []);

    return (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className="flex flex-col text-xs w-full h-full">
            <div className="rounded-lg  mt-8 m-auto p-5 bg-white text-black">
              <pre>
                <code>
                  {workletCode}
                </code>
              </pre>
            </div>
          </main>
        </>
    );
}
